[project]
name = "probe-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cadquery>=2.6.1",
    "numpy>=2.3.5",
    "pymeshfix>=0.17.1",
    "scikit-image>=0.25.2",
    "tqdm>=4.67.1",
    "trimesh>=4.10.0",
]
